# Usa l'immagine ufficiale di Node.js come base per l'immagine
FROM node:18.14.2-alpine AS build

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Aggiungi il middleware per instradare le richieste API
RUN npm install express http-proxy-middleware cors
COPY middleware.js .

ENV NODE_ENV development

EXPOSE 3000

# Avvia il middleware
CMD ["sh", "-c", "node middleware.js --host 0.0.0.0"]
